name: Deploy Server to Cloud Run from Source
on: [push]

jobs:
    deploy:
        name: Deploy python-server
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/python-server' || github.ref == 'refs/heads/gh-actions'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: actions-hub/gcloud@master
              env:
                PROJECT_ID: ${{secrets.GCP_PY_PROJECT_ID}}
                APPLICATION_CREDENTIALS: ${{secrets.GCP_SA_KEY}}
              with:
                args: builds submit --dir python-server